### ISSUE TITLE
Confirm that Superset instance on GCE can be deleted

### ISSUE THREAD

**Issue by patcon** [datatogether/datatogether-superset#1]
Google Cloud Engine is hosting our previous Superset instance that @sonalranjit set up for us. Sonal has, to my understanding, configured this Heroku instance with all the same data sources and dashboards.

Did I get that right sonal? Can you confirm that we're good to completely blow away the old server?

Thanks!

**Comment by patcon** [comment]
cc: @dcwalk @mr0grog

Related `web-monitoring` agenda: https://hackmd.io/s/Syq3FzhBW

**Comment by sonalranjit** [comment]
@patcon yes it can be completely blown away, the vm's name is sonal-vm-1
