### ISSUE TITLE
Can we archive this repo?

### ISSUE THREAD

**Issue by lightandluck** [datatogether/datatogether-superset#5]
@b5 @titaniumbones @dcwalk @patcon 

I'm not sure what this repo was for and haven't heard any discussion around it. Last commit was also from 2017. Just checked and the Heroku app that the README points to is not linked to EDGI's Heroku account. 

Been getting notifications about security vulnerabilities for this repo, but not sure if it's worth addressing. Is this something we can archive? Is there something we should grab or document before doing so?

**Comment by patcon** [comment]
Hi Kevin! I believe I'd have the most context, and I think you're good to ~~shut it down~~ archive it :)

**Comment by b5** [comment]
yep! let's archive!

**Comment by lightandluck** [comment]
Thanks all, will do 👍
